plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'mruby/**/*'
    - 'mitamae-build/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/recipes/**/*'
    - 'spec/plugins/**/*'
    - 'spec/windows/**/*'
    - 'tools/**/*'
    - '**/*.erb'
    - '**/*.rake'
    - 'mrblib/**/*.rb'  # mruby code has different constraints

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/LineLength:
  Max: 120
  AllowURI: true
  AllowCopDirectives: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '()'
    '%I': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false